config/routes.rb
Rails.application.routes.draw do
  # mount ImageUploader::UploadEndpoint => "/images/upload"
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations" }


  get '/users/profile', to: 'users#profile', as: 'user_profile'
  put '/users/profile', to: 'users#update_profile', as: 'user_update_profile'

  get '/users/advertisers', to: 'users#advertisers', as: 'user_advertisers'
  put '/users/advertisers', to: 'users#update_advertisers', as: 'user_update_advertisers'
  
  get '/users/products', to: 'users#products', as: 'user_products'
  put '/users/products', to: 'users#update_products', as: 'user_update_products'

  get '/users/flagged', to: 'users#flagged', as: 'user_flagged'
  put '/users/flagged', to: 'users#update_flagged', as: 'user_update_flagged'

  get '/users/forum_posts', to: 'users#forum_posts', as: 'user_forum_posts'
  
  get '/users/banners', to: 'users#banners', as: 'user_banners'
  post '/users/banners', to: 'users#update_banners', as: 'user_update_banners'

  get '/users/categories', to: 'users#categories', as: 'user_categories'
  put '/users/categories', to: 'users#update_categories', as: 'user_update_categories'
  post '/users/categories', to: 'users#create_categories', as: 'user_create_categories'

  get '/users/forum_categories', to: 'users#forum_categories', as: 'user_forum_categories'
  put '/users/forum_categories', to: 'users#update_forum_categories', as: 'user_update_forum_categories'
  post '/users/forum_categories', to: 'users#create_forum_categories', as: 'user_create_forum_categories'
  
  resources :forum_threads, :path => 'discussions' do #url = community
    resources :forum_posts, module: :forum_threads
  end

  resources :markets, :path => 'marketplace' #url = marketplace

  get '', to: 'products#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  post '/products/flag', to: 'products#flag', as: 'product_flag'
  resources :products
  
  resources :users do
    collection do
      post :import
    end
  end

  root to: "markets#index"
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :images, ImageUploader
  acts_as_paranoid

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  # accepts_nested_attributes_for :markets
  
  validates :email, email_format: true
  validates_uniqueness_of :username
  validates_format_of :username, :with => /\A[a-zA-Z0-9]*\z/, :message => "letters and numbers only"
  validates_format_of :facebook, :instagram, :twitter, :with => /\A[a-zA-Z0-9._]*\z/, :message => "letters, numbers, periods, and underscores only"
  validates_format_of :first_name, :last_name, :with => /\A[a-zA-Z]*\z/, :message => "invalid entry, only letters allowed"

  belongs_to :market
  has_many :forum_threads
  has_many :forum_posts
  
  has_many :products


  def self.assign_from_row(row)
    user = User.where(email: row[:email]).first_or_initialize
    user.assign_attributes row.to_hash.slice(:first_name, :last_name, :market_id, :phone_number, :images, :admin, :is_advertiser, :is_mod, :username, :school_class, :school_program, :facebook, :instagram, :twitter, :snapchat)
  end

  def self.to_csv
    attributes = %w{id email name}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  def name
    if deleted_at?
      "Deleted User"
    else
      "#{first_name} #{last_name}"
    end
  end


  # private 

  # def validate_email
  #   return if $current_market.blank? || $current_market.email_address_type?
  #   return if email.include?($current_market.email_address_type)
  #   errors.add(:email, "must be your student email address (ex: sshon@#{$current_market.email_address_type})")
  # end

end

app/models/user/import.rb
class User::Import
  include ActiveModel::Model
  attr_accessor :file, :imported_count

  def process!
    @imported_count = 0
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      user = User.assign_from_row(row)
      if user.save
        @imported_count += 1
      else
        errors.add :base, "Line #{$.} - #{user.errors.full_messages.join(",")}"
      end
    end
  end

  def save
    process!
    errors.none?
  end
end

app/controllers/users/banners_controller.rb
class Users::BannersController < ApplicationController


end

app/controllers/users/categories_controller.rb
class Users::CategoriesController < ApplicationController


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    root_path
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message!(:notice, flash_message)
        sign_in(resource_name, resource)
      else
        set_flash_message!(:notice, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    super
    $current_market = set_market
  end

  def edit
    super
    $current_market = set_market
  end

  def after_sign_up_path_for(resource)
		edit_user_registration_path
  end

	private 
    def update_resource(resource, params)
      resource.update_without_password(params)
      # redirect_to new_post_path - need to fix
    end

    def registration_params
  		params.require(:user).permit(:email, :password, :password_confirmation, :images, :first_name, :last_name, :phone_number, :username, :market_id, :facebook, :instagram, :twitter, :snapchat)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
	def create
	    self.resource = warden.authenticate!(auth_options)
	    # set_flash_message!(:notice, :signed_in) # deleted to show alert messages
	    sign_in(resource_name, resource)
	    yield resource if block_given?
	    respond_with resource, location: after_sign_in_path_for(resource)
	end


	def after_sign_in_path_for(resource)
		if current_user.admin == true
			flash[:alert] = "Signed in successfully."
			stored_location_for(resource) || root_path
		elsif current_user.market_id != @market.id
			# current_user.deactivate_user(@user)
		    sign_out(@user)
		    flash[:alert] = "Email is not a valid email address."
			new_user_session_path
		else
			flash[:alert] = "Signed in successfully."
			stored_location_for(resource) || root_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # helper_method :current_market
  before_action :authenticate_user!, :set_user
  helper_method :set_market


  # load_and_authorize_resource
  # def index
  #   @users = User.all
  #   @import = User::Import.new

  #   respond_to do |format|
  #     format.html
  #     format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
  #   end
  # end

  # def import
  #   @import = User::Import.new user_import_params
  #   if @import.save
  #     redirect_to users_path, notice: "Imported #{@import.imported_count} users"
  #   else
  #     @users = User.all
  #     flash[:alert] = "There were #{@import.errors.count} errors with your CSV file"
  #     render action: :index
  #   end
  # end

  
  # def become
  #   return unless current_user.admin?
  #   sign_in(:user, User.find(params[:id]))
  #   redirect_to root_url # or user_root_url
  # end
  def index
    @users = User.all
  end

  def profile
    @user = current_user
  end

  def advertisers
    if current_user.admin?
      @users = User.all
    else 
      redirect_to root_path
    end
  end

  def update_advertisers
    if current_user.admin?
      @user = User.find(params[:format])
        params[:user].delete(:password) if params[:user][:password].blank?
        params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
      if @user.update(advertiser_params)
        flash[:notice] = "Successfully updated User."
        redirect_to user_advertisers_path
      else
        flash[:alert] = @user.errors.full_messages
        redirect_to user_advertisers_path
      end
    else 
      redirect_to root_path
    end
  end

  def flagged
    if current_user.admin? || current_user.is_mod?
      @flags = Flag.all.order("created_at DESC")
    else 
      redirect_to root_path
    end
  end

  def update_flagged
    set_product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to :user_flagged, notice: 'Flagged product was successfully deleted.'}
        format.json { render :user_flagged, status: :ok, location: :user_flagged }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def products
    if current_user.admin?
      @products = Product.all.where(market: @market).order("created_at DESC")
    else 
      @products = current_user.products.where(market: @market).order("created_at DESC")
    end
  end

  def update
    set_product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to :user_products, notice: 'Product was successfully deleted.'}
        format.json { render :user_products, status: :ok, location: :user_products }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def banners 
    if current_user.admin?
      @banner = Banner.new
    else 
      redirect_to root_path
    end
  end

  def update_banners
    set_banner
    if current_user.admin?
      respond_to do |format|
        if @banner.update(banner_params)
          format.html { redirect_to :user_banners, notice: 'Banner was successfully updated.' }
          format.json { render :user_banners, status: :ok, location: :user_banners }
        else
          format.html { render :edit }
          format.json { render json: @banner.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to root_path
    end
  end

  def categories 
    # set_category
    if current_user.admin?
      @categories = Category.all.where(market_id: @market).order("created_at DESC")
      @category = Category.new
    else 
      redirect_to root_path
    end
  end

  def create_categories
    if current_user.admin?
      @category = Category.create(category_params)
      @category.market_id = @market.id

      if @category.save
        redirect_to user_categories_path
      else
        render action: :new
      end
    end
  end

  def update_categories
    set_category
    if current_user.admin?
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to :user_categories, notice: 'Category was successfully updated.' }
          format.json { render :user_categories, status: :ok, location: :user_categories }
        else
          byebug
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to root_path
    end
  end

  def forum_categories 
    # set_forum_category
    if current_user.admin?
      @forum_categories = ForumCategory.all.where(market_id: @market).order("created_at DESC")
      @forum_category = ForumCategory.new
    else 
      redirect_to root_path
    end
  end

  def create_forum_categories
    if current_user.admin?
      @forum_category = ForumCategory.create(forum_category_params)
      @forum_category.market_id = @market.id

      if @forum_category.save
        redirect_to user_forum_categories_path
      else
        render action: :new
      end
    end
  end

  def update_forum_categories
    set_forum_category
    if current_user.admin?
      respond_to do |format|
        if @forum_category.update(forum_category_params)
          format.html { redirect_to :user_forum_categories, notice: 'Category was successfully updated.' }
          format.json { render :user_forum_categories, status: :ok, location: :user_forum_categories }
        else
          byebug
          format.html { render :edit }
          format.json { render json: @forum_category.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to root_path
    end
  end


  def forum_posts 
    @forum_posts = current_user.forum_posts
  end



  def messages

  end

  private
    def set_user
      @user = current_user.id
    end 

    def set_users
      @users = User.all
    end

    def set_product
      @product = Product.find_by!(id: params[:product][:id], market: @market)
    rescue
      flash[:alert] = "Product could not be found"
      redirect_to root_path
    end

    def set_banner
      @banner = Banner.where(user_id: @user, market: @market).first_or_create
    end

    def set_category
      @category = Category.find_by!(market_id: @market)
    end

    def set_forum_category
      @forum_category = ForumCategory.find_by!(market_id: @market)
    end
    
    def user_import_params
      params.require(:user_import).permit(:file)
    end
    
    def advertiser_params
      params.require(:user).permit(:is_advertiser)
    end

    def product_params
      params.require(:product).permit(:user_id, :title, :description, :price, :market_id, :category_id, :expire_date)
    end

    def banner_params
      params.require(:banner).permit(:user_id, :market_id, :product_index, :product_show, :product_new, :forum_index, :forum_show, :forum_new, :account_profile)
    end

    def category_params
      params.require(:category).permit(:market_id, :category_name, :group_id)
    end

    def forum_category_params
      params.require(:forum_category).permit(:market_id, :category_name, :group_id)
    end
end

app/views/users/_sidenav.html.erb
<div class="col-sm-3 col-md-2 hidden-xs hidden-sm sidenav-container-users">
	<div class="sidenav">
		<div class="sidenav-nav sidenav-categories">
			<li class="<%= active_class(edit_user_registration_path) %> list-group-item list-group-item-action">
				<%= link_to "Profile", edit_user_registration_path, class: "list-group-item list-group-item-action" %> 
			</li>
			<li class="<%= active_class(user_products_path) %> list-group-item list-group-item-action">
				<%= link_to "Products", user_products_path, class: "list-group-item list-group-item-action" %>
			</li>
<!-- 			<li class="<%= active_class(user_forum_posts_path) %> list-group-item list-group-item-action">
				<%= link_to "Forum Posts", user_forum_posts_path, class: "list-group-item list-group-item-action" %>
			</li> -->
			<% if current_user.admin? || current_user.is_mod? %>
				<li class="<%= active_class(user_flagged_path) %> list-group-item list-group-item-action">
					<%= link_to "Flagged Products", user_flagged_path, class: "list-group-item list-group-item-action" %>
				</li>

				<li class="<%= active_class(user_categories_path) %> list-group-item list-group-item-action">
					<%= link_to "Product Categories", user_categories_path, class: "list-group-item list-group-item-action" %>
				</li>

				<li class="<%= active_class(user_forum_categories_path) %> list-group-item list-group-item-action">
					<%= link_to "Forum Categories", user_forum_categories_path, class: "list-group-item list-group-item-action" %>
				</li>
			<% end %>

			<% if current_user.admin? %>
				<li class="<%= active_class(user_banners_path) %> list-group-item list-group-item-action">
					<%= link_to "Banners", user_banners_path, class: "list-group-item list-group-item-action" %>
				</li>
				<li class="<%= active_class(user_advertisers_path) %> list-group-item list-group-item-action">
					<%= link_to "Advertisers", user_advertisers_path, class: "list-group-item list-group-item-action" %>
				</li>
			<% end %>
		</div>
	</div>
</div>	

<div class="visible-xs visible-sm">
    <div class="navbar-header">
      <button class="col-xs-12 sidenav-container sidenav-container-filters navbar-toggle" type="button" data-toggle="collapse" data-target=".cs-navbar-collapse">
        <h6 class="sidenav-filters-header"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Settings</h6>
      </button>
    </div>

    <nav class="collapse navbar-collapse cs-navbar-collapse " role="navigation">
      <ul class="nav navbar-nav user-nav">
  		<li class="<%= active_class(edit_user_registration_path) %> list-group-item list-group-item-action">
			<%= link_to "Profile", edit_user_registration_path, class: "list-group-item list-group-item-action" %> 
		</li>
		<li class="<%= active_class(user_products_path) %> list-group-item list-group-item-action">
			<%= link_to "Products", user_products_path, class: "list-group-item list-group-item-action" %>
		</li>
<!-- 			<li class="<%= active_class(user_forum_posts_path) %> list-group-item list-group-item-action">
			<%= link_to "Forum Posts", user_forum_posts_path, class: "list-group-item list-group-item-action" %>
		</li> -->
		<% if current_user.admin? || current_user.is_mod? %>
			<li class="<%= active_class(user_flagged_path) %> list-group-item list-group-item-action">
				<%= link_to "Flagged Products", user_flagged_path, class: "list-group-item list-group-item-action" %>
			</li>

			<li class="<%= active_class(user_categories_path) %> list-group-item list-group-item-action">
				<%= link_to "Product Categories", user_categories_path, class: "list-group-item list-group-item-action" %>
			</li>

			<li class="<%= active_class(user_forum_categories_path) %> list-group-item list-group-item-action">
				<%= link_to "Forum Categories", user_forum_categories_path, class: "list-group-item list-group-item-action" %>
			</li>
		<% end %>

		<% if current_user.admin? %>
			<li class="<%= active_class(user_banners_path) %> list-group-item list-group-item-action">
				<%= link_to "Banners", user_banners_path, class: "list-group-item list-group-item-action" %>
			</li>
			<li class="<%= active_class(user_advertisers_path) %> list-group-item list-group-item-action">
				<%= link_to "Advertisers", user_advertisers_path, class: "list-group-item list-group-item-action" %>
			</li>
		<% end %>
	  </ul>
    </nav>
</div>

app/views/users/advertisers.html.erb
<div class="content-container">
	<%= render partial: "users/sidenav" %>

	<div class="container col-md-10 col-sm-12 container-mobile-product">
		<h1>Set Advertisers</h1>
		<table class="table-striped">
			<tr class="user-setting-tr-header">
			    <th>ID</th>
			    <th>Advertiser</th>
			    <th>Email</th>
			    <th>Market</th>
			    <th>Update</th>
	  		</tr>
			<% @users.each do |user| %>
				<%= form_for(user, as: :user, :url => user_update_advertisers_path(user), :html => { :method => :put, id: user.id }) do |f| %>
			  	<% if user.errors.any? %>

			    	<div id="error_explanation">
			      		<h2><%= pluralize(user.errors.count, "error") %> prohibited this listing from being saved:</h2>

			      	<ul>
			      		<% @user.errors.full_messages.each do |message| %>
			        		<li><%= message %></li>
			      		<% end %>
			      	</ul>
			    	</div>
			 	<% end %>

			<!-- view only none expired posts -->
			
			
			<!-- link to update user -->
			<tr class="user-setting-tr">
				<td><%= user.id %></td>
				<td><%= user.is_advertiser %></td>
				<td><%= user.email %></td>
				<td><%= user.market_id %></td>
				<%= f.hidden_field :is_advertiser, value: true %>
			    <%= f.hidden_field :user_id, value: user.id %>
			    <td><%= f.submit "Update", class: "btn btn-danger" %></td>
			</tr>

			<!-- expire user -->
			<% end %>
			<% end %>
		</table>
	</div>
</div>

app/views/users/categories.html.erb
<div class="content-container">
  <%= render partial: "users/sidenav" %>

  <div class="container col-md-10 col-sm-12 container-mobile-product">
    <h1>Product Categories</h1>
      <% @categories.each do |category| %>
        <%= form_for category, url: user_update_categories_path, method: :put, html: {id: category.id} do |f| %>
            <% if category.errors.any? %>
              <div id="error_explanation">
                  <h2><%= pluralize(category.errors.count, "error") %> prohibited this listing from being saved:</h2>

                <ul>
                  <% category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <%= f.text_field :category_name, class: "" %>
          <%= f.submit "Update", class: "btn btn-danger" %>
        <% end %>
      <% end %>

    <h1>Create Categories</h1>

    <%= form_for(@category, url: user_create_categories_path, :html => {:multipart => true})  do |f| %>
      <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this listing from being saved:</h2>

          <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h4>Category</h4>
      <div class="form-group">
        <%= f.text_field :category_name, autofocus: true, placeholder: "Add Category", class: "form-control" %>
      </div>

      <%= f.hidden_field :market, value: $current_market %>
      <div class="form-group">
        <%= f.button "Create Category", class: "btn btn-primary", 'data-disable-with' => "Creating Category...".html_safe, style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/flagged.html.erb
<div class="content-container">
	<%= render partial: "users/sidenav" %>

	<div class="container col-md-10 col-sm-12 container-mobile-product">
		<h1>Flagged Products</h1>
		<table class="table-striped">
			<tr class="user-setting-tr-header">
			    <th>Status</th>
			    <th>Action</th>
			    <th>Title</th>
			    <th>Category</th>
			    <th>Posted Date</th>
			    <th>Expired Date</th>
			    <th>Archive</th>
	  		</tr>
			<% @flags.each do |flag| %>
				<%= form_for flag.product, url: user_update_flagged_path, method: :put, html: {id: flag.product.id} do |f| %>
				  	<% if flag.product.errors.any? %>
				    	<div id="error_explanation">
				      		<h2><%= pluralize(flag.product.errors.count, "error") %> prohibited this listing from being saved:</h2>

				      	<ul>
				      		<% flag.product.errors.full_messages.each do |message| %>
				        		<li><%= message %></li>
				      		<% end %>
				      	</ul>
				    	</div>
				 	<% end %>

			<!-- view only none expired posts -->
			  	<tr class="user-setting-tr">
				    <% if flag.product.expire_date.nil? || flag.product.expire_date > Time.now %>
				    	<td>Active</td>
				    	<td>
					    	<%= link_to edit_product_path(flag.product) do %>
					    		<b>Edit</b>
					    	<% end %>
				    	</td>
					<% else %>
						<td>Expired</td>
							<td>
					    	<%= link_to edit_product_path(flag.product) do %>
					    		<b>Repost</b>
					    	<% end %>
					    </td>
					<% end %>
				    <td><%= link_to product_path(flag.product) do %><%= flag.product.title %><% end %></td>
				    <td><%= flag.product.category.category_name %></td>
				    <td><%= local_time_ago flag.product.created_at.to_formatted_s(:db)  %></td>
					<% if flag.product.expire_date.present? %>
						<td><%= flag.product.expire_date > Time.now ? "" : local_time_ago(flag.product.expire_date.to_formatted_s(:db)) %></td>
					<% else %>
						<td></td>
					<% end %>

				    <!-- link to update product -->
					<%= f.hidden_field :id, value: flag.product.id %>
				    <%= f.hidden_field :expire_date, value: Time.now %>

				    <!-- expire product -->
				    <td>
				    	<%= f.submit "Archive", class: 'btn btn-danger' %>
				    </td>
			  	</tr>
				<% end %>
			<% end %>
		</table>
	</div>
</div>

app/views/users/forum_categories.html.erb
<div class="content-container">
  <%= render partial: "users/sidenav" %>

  <div class="container col-md-10 col-sm-12 container-mobile-product">
    <h1>Forum Categories</h1>
      <% @forum_categories.each do |forum_category| %>
        <%= form_for forum_category, url: user_update_forum_categories_path, method: :put, html: {id: forum_category.id} do |f| %>
            <% if forum_category.errors.any? %>
              <div id="error_explanation">
                  <h2><%= pluralize(forum_category.errors.count, "error") %> prohibited this listing from being saved:</h2>

                <ul>
                  <% forum_category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
              <%= f.text_field :category_name, class: "" %>
              <%= f.submit "Update", class: "btn btn-danger" %>
        <% end %>
      <% end %>

    <h1>Create Forum Categories</h1>

    <%= form_for(@forum_category, url: user_create_forum_categories_path, :html => {:multipart => true})  do |f| %>
      <% if @forum_category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@forum_category.errors.count, "error") %> prohibited this listing from being saved:</h2>

          <ul>
          <% @forum_category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h4>Category</h4>
      <div class="form-group">
        <%= f.text_field :category_name, autofocus: true, placeholder: "Add Category", class: "form-control" %>
      </div>

      <%= f.hidden_field :market, value: $current_market %>
      <div class="form-group">
        <%= f.button "Create Forum Category", class: "btn btn-primary", 'data-disable-with' => "Creating Forum Category...".html_safe, style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/forum_posts.html.erb
<div class="content-container">
	<%= render partial: "users/sidenav" %>

	<div class="container col-md-10 col-sm-12 container-mobile-product">
	  <h1>Previous Posts</h1>
	    <% @forum_posts.each do |forum_post| %>
	      <tr>
	        <td><%= forum_post.id %></td>
	        <td><%= forum_post.body %></td>
	      </tr>
	    <% end %>
	</div>
</div>

app/views/users/products.html.erb
<div class="content-container">
	<%= render partial: "users/sidenav" %>

	<div class="container col-md-10 col-sm-12 container-mobile-product">
		<h1>Previous Products</h1>
		<table class="table-striped">
			<tr class="user-setting-tr-header">
			    <th>Status</th>
			    <th>Action</th>
			    <th>Title</th>
			    <th>Category</th>
			    <th>Posted Date</th>
			    <th>Expired Date</th>
			    <th>Archive</th>
	  		</tr>
			<% @products.each do |product| %>
				<%= form_for product, url: user_update_products_path, html: {id: product.id} do |f| %>
				  	<% if product.errors.any? %>
				    	<div id="error_explanation">
				      		<h2><%= pluralize(product.errors.count, "error") %> prohibited this listing from being saved:</h2>

				      	<ul>
				      		<% @product.errors.full_messages.each do |message| %>
				        		<li><%= message %></li>
				      		<% end %>
				      	</ul>
				    	</div>
				 	<% end %>

			<!-- view only none expired posts -->
			  	<tr class="user-setting-tr">
				    <% if product.expire_date.nil? || product.expire_date > Time.now %>
				    	<td>Active</td>
				    	<td>
					    	<%= link_to edit_product_path(product) do %>
					    		<b>Edit</b>
					    	<% end %>
				    	</td>
					<% else %>
						<td>Expired</td>
							<td>
					    	<%= link_to edit_product_path(product) do %>
					    		<b>Repost</b>
					    	<% end %>
					    </td>
					<% end %>
				    <td><%= link_to product_path(product) do %><%= product.title %><% end %></td>
				    <td><%= product.category.category_name %></td>
				    <td><%= local_time_ago product.created_at.to_formatted_s(:db)  %></td>
					<% if product.expire_date.present? %>
						<td><%= product.expire_date > Time.now ? "" : local_time_ago(product.expire_date.to_formatted_s(:db)) %></td>
					<% end %>

				    <!-- link to update product -->
					<%= f.hidden_field :id, value: product.id %>
				    <%= f.hidden_field :expire_date, value: Time.now %>

				    <!-- expire product -->
				    <td>
				    	<%= f.submit "Archive", class: 'btn btn-danger' %>
				    </td>
			  	</tr>
				<% end %>
			<% end %>
		</table>
	</div>
</div>