config/routes.rb
Rails.application.routes.draw do
  # mount ImageUploader::UploadEndpoint => "/images/upload"
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations" }


  get '/users/profile', to: 'users#profile', as: 'user_profile'
  put '/users/profile', to: 'users#update_profile', as: 'user_update_profile'

  get '/users/advertisers', to: 'users#advertisers', as: 'user_advertisers'
  put '/users/advertisers', to: 'users#update_advertisers', as: 'user_update_advertisers'
  
  get '/users/products', to: 'users#products', as: 'user_products'
  put '/users/products', to: 'users#update_products', as: 'user_update_products'

  get '/users/flagged', to: 'users#flagged', as: 'user_flagged'
  put '/users/flagged', to: 'users#update_flagged', as: 'user_update_flagged'

  get '/users/forum_posts', to: 'users#forum_posts', as: 'user_forum_posts'
  
  get '/users/banners', to: 'users#banners', as: 'user_banners'
  post '/users/banners', to: 'users#update_banners', as: 'user_update_banners'

  get '/users/categories', to: 'users#categories', as: 'user_categories'
  put '/users/categories', to: 'users#update_categories', as: 'user_update_categories'
  post '/users/categories', to: 'users#create_categories', as: 'user_create_categories'

  get '/users/forum_categories', to: 'users#forum_categories', as: 'user_forum_categories'
  put '/users/forum_categories', to: 'users#update_forum_categories', as: 'user_update_forum_categories'
  post '/users/forum_categories', to: 'users#create_forum_categories', as: 'user_create_forum_categories'
  
  resources :forum_threads, :path => 'discussions' do #url = community
    resources :forum_posts, module: :forum_threads
  end

  resources :markets, :path => 'marketplace' #url = marketplace

  get '', to: 'products#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  post '/products/flag', to: 'products#flag', as: 'product_flag'
  resources :products
  
  resources :users do
    collection do
      post :import
    end
  end

  root to: "markets#index"
end

app/views/shared/_footer.html.erb
<footer class="footer col-sm-12" style="border-top: 5px solid transparent; -moz-border-image: -moz-linear-gradient(left, <%= @market.second_color %> 0%, <%= @market.first_color %> 100%) !important; -webkit-border-image: -webkit linear-gradient(left, <%= @market.second_color %> 0%, <%= @market.first_color %> 100%) !important; border-image: linear-gradient(to right, <%= @market.second_color %> 0%, <%= @market.first_color %> 100%) !important; border-image-slice: 1 !important;">
	<div class="footer-div">
	<h6>This is a beta. Slashform is still in the works. We'd love your feedback.<br>(Yea, that's a haiku <%= markdownify ':sunglasses:' %>)</h6>
	<h6><a href="mailto:feedback@slashform.com?Subject=Product%20Feedback">feedback@slashform.com</a></h6>
	</div>
</footer>

app/views/shared/_navbar.html.erb
<header class="navbar <%= content_for?(:navbar_style) ? yield(:navbar_style) : "navbar-default" %> navbar-static-top" role="banner" style="background: #fff; border-bottom: 5px solid; -moz-border-image: -moz-linear-gradient(left, <%= @market.second_color %> 0%, <%= @market.first_color %> 100%) !important; -webkit-border-image: -webkit linear-gradient(left, <%= @market.second_color %> 0%, <%= @market.first_color %> 100%) !important; border-image: linear-gradient(to right, <%= @market.second_color %> 0%, <%= @market.first_color %> 100%) !important; border-image-slice: 1 !important;" >
  <div class="content-container navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do %>
        SlashForm
      <% end %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li class="<%= active_class(products_path) %> <%= active_class(root_path) %> list-group-item list-group-item-action list-group-left"><%= link_to "Marketplace", products_path %></li>
        <li class="<%= active_class(forum_threads_path) %> list-group-item list-group-item-action list-group-left"><%= link_to "Discussions", forum_threads_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user.present? || current_user.is_advertiser != true %> 
          <li class="<%= active_class(forum_threads_path) %> list-group-item list-group-item-action list-group-right" style="color: <%= @market.first_color %>"><%= link_to "Post Thread", new_forum_thread_path, style: "color: #{@market.first_color}" %></li>
        <% end %>
        <% if !current_user.present? || current_user.is_advertiser != true %> 
          <li class="<%= active_class(products_path) %> <%= active_class(root_path) %> list-group-item list-group-item-action list-group-right" style="color: <%= @market.first_color %>"><%= link_to "Post Product", new_product_path, style: "color: #{@market.first_color}" %></li>
        <% else %>
          <li class="<%= active_class(products_path) %> <%= active_class(root_path) %> list-group-item list-group-item-action list-group-right" ><%= link_to "Post Ad", new_product_path, style: "color: #{@market.first_color}" %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>