config/routes.rb
Rails.application.routes.draw do
  # mount ImageUploader::UploadEndpoint => "/images/upload"
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations" }


  get '/users/profile', to: 'users#profile', as: 'user_profile'
  put '/users/profile', to: 'users#update_profile', as: 'user_update_profile'

  get '/users/advertisers', to: 'users#advertisers', as: 'user_advertisers'
  put '/users/advertisers', to: 'users#update_advertisers', as: 'user_update_advertisers'
  
  get '/users/products', to: 'users#products', as: 'user_products'
  put '/users/products', to: 'users#update_products', as: 'user_update_products'

  get '/users/flagged', to: 'users#flagged', as: 'user_flagged'
  put '/users/flagged', to: 'users#update_flagged', as: 'user_update_flagged'

  get '/users/forum_posts', to: 'users#forum_posts', as: 'user_forum_posts'
  
  get '/users/banners', to: 'users#banners', as: 'user_banners'
  post '/users/banners', to: 'users#update_banners', as: 'user_update_banners'

  get '/users/categories', to: 'users#categories', as: 'user_categories'
  put '/users/categories', to: 'users#update_categories', as: 'user_update_categories'
  post '/users/categories', to: 'users#create_categories', as: 'user_create_categories'

  get '/users/forum_categories', to: 'users#forum_categories', as: 'user_forum_categories'
  put '/users/forum_categories', to: 'users#update_forum_categories', as: 'user_update_forum_categories'
  post '/users/forum_categories', to: 'users#create_forum_categories', as: 'user_create_forum_categories'
  
  resources :forum_threads, :path => 'discussions' do #url = community
    resources :forum_posts, module: :forum_threads
  end

  resources :markets, :path => 'marketplace' #url = marketplace

  get '', to: 'products#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  post '/products/flag', to: 'products#flag', as: 'product_flag'
  resources :products
  
  resources :users do
    collection do
      post :import
    end
  end

  root to: "markets#index"
end

app/models/product.rb
class Product < ApplicationRecord

	mount_uploaders :images, ImageUploader
	# include ImageUploader::Attachment.new(:image)
	

	belongs_to :user
	belongs_to :market
	belongs_to :category

	has_many :flags

	# validates :title, presence: true, :email_format => true
	# # validates :title, presence: true
	# validates :category_id, presence: true
	# validates :price, presence: true
	# validates :description, presence: true

	def user
    	User.unscoped { super }
   	end

   	def to_param
    	"#{id}-#{title}".parameterize
  	end
end

app/controllers/products/images_controller.rb
class Products::ImagesController < ApplicationController
  before_action :set_product
  # before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = @product.images.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json

  def create
    @image = @product.images.new image_params

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = @product.images.find(params[:id])
    end    

    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:product_id, :image, :image_data)
    end
end

app/controllers/products_controller.rb
#global
$max_products = 5
$days_posted = 14
$pagination_count = 25


class ProductsController < ApplicationController
  # before_action :set_market
  before_action :set_product, except: [:index, :new, :create]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @q = Product.search(params[:q])

    @products = Product.paginate(page: params[:page], per_page: $pagination_count).where("market_id = ? AND (products.expire_date IS null OR products.expire_date > ?)", @market.id, Time.now)

    if params[:q].present?
      @products = @q.result.paginate(page: params[:page], per_page: $pagination_count).where("market_id = ? AND (products.expire_date IS null OR products.expire_date > ?)", @market.id, Time.now)
    end
    @flag = Flag.new
    @user = current_user

    # if params[:location].present?
    #   @products = @products.near(params[:location]).where(market: @market)
    # end

    # @products = @products.paginate(:page => params[:page], :per_page => 30)
  end

  def flag
    @flag = Flag.new(flag_params)
    if @flag.save
      flash[:alert] = "Product has been reported."
      redirect_to root_path
    else
      flash[:alert] = "Could not flag product."
    end
  end

  # What is this supposed to do again?
  # def search
  #   index
  #   render :index
  # end

  def show
    @product = Product.find(params[:id])
    @user = current_user
  end

  def new
    @product = Product.new
    @user = current_user
    @products = current_user.products.count
  end

  def edit
    @products = current_user.products.count
  end

  def create
    @product = current_user.products.build(product_params)
    @product.market_id = @market.id
    @product.expire_date = $days_posted.days.from_now

    if @product.save
      redirect_to @product
    else
      render action: :new
    end
  end

  def update
    @product.expire_date = $days_posted.days.from_now
    respond_to do |format|
      if @product.update(product_params)
        @product.save
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def set_market
    @market = Market.find_by_subdomain!(request.subdomain) unless request.subdomain.empty?
  end

  def set_product
    @product = Product.find_by!(id: params[:id], market: @market)
  rescue
    flash[:alert] = "Product could not be found"
    redirect_to root_path
  end

  def product_params
    params.require(:product).permit(:user_id, :title, :description, :price, :market_id, :category_id, :expire_date, {images:[]}, :contact_pref, :contact_by_email, :contact_by_phone, user_attributes: [:phone_number])
  end

  def flag_params
    params.require(:flag).permit(:user_id, :product_id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
	def categories_for_select
	  Category.all.collect { |m| [m.category_name, m.id] }
	end
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:multipart => true})  do |f| %>
  <% if @product.errors.any? %>
<!--     <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul> -->
      <% @product.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      <!-- </ul> -->
    </div>
  <% end %>


<!-- WHY DID I EMAIL MASK? -->
  <div class="form-group">
    <div><%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, placeholder: "Title", class: "form-control", required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div><%= f.label :price %><br />
      <div class="form-group" id="input-container">
        <%= f.number_field :price, required: true, placeholder: "Price", class: "form-control", id: "input-social" %>
        <i class="fa fa-usd" aria-hidden="true" id="input-social-icon"></i>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div><%= f.label :category %><br />
      <div class="form-group">
      <%= f.collection_select :category_id, Category.order(:category_name), :id, :category_name, {prompt: true}, {class: "form-control", required: true} %>
      </div>
    </div>
    </div>
  </div>

  <div class="form-group">
    <div><%= f.label :description %><br />
    <%= f.trix_editor :description, required: true, placeholder: "Description", rows: 20, class: "form-control" %>
  </div>

  <div class="form-group">
    <% if @product.images? %>
      <% @product.images.each do |p| %>
        <%= image_tag(p.url, class: "image-container-preview") %>
      <% end %>
    <% end %>
    <div id="preview"></div>
    <%= f.file_field :images, :onchange => "previewFiles()", multiple: true, placeholder: "Image", accept: ".jpg, .jpeg, .gif, .png", class: "form-control", id: "image-form" %>
    <%= f.hidden_field :images_cache, multiple: true %>
  </div>
  <hr>
  <h4>Contact Preference</h4>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.check_box :contact_by_email, placeholder: "contact via email", rows: 10, class: "form-product-contact", disabled: true %> Email: <b><%= current_user.email %></b>
        <br>
        <% if current_user.phone_number? %>
          <%= f.check_box :contact_by_phone, placeholder: "contact via phone", rows: 10, class: "form-product-contact", checked: true %> Phone number<a href="#" class="tooltip-icon" data-toggle="tooltip" title="Add a phone number if you'd like the option to be contacted via phone. Standard rates apply."> <i class="fa fa-info-circle" aria-hidden="true"></i></a> : <b><%= current_user.phone_number %></b>
        <% else %>
          <%= f.check_box :contact_by_phone, placeholder: "contact via phone", rows: 10, class: "form-product-contact", id: "form-phone-checkbox" %> Phone number<a href="#" class="tooltip-icon" data-toggle="tooltip" title="Add a phone number if you'd like the option to be contacted via phone. Standard rates apply."> <i class="fa fa-info-circle" aria-hidden="true"></i></a><br /> <%= f.phone_field :contact_pref, placeholder: "(XXX) XXX-XXXX", rows: 10, class: "form-control form-phone-form" %>
        <% end %>
      </div>
    </div>
  </div>  

  <hr>
  <div class="form-group">
    <h6>Product will stay posted for <%= $days_posted %> days.</h6>
    <!-- language is in js -->
    <p id="fp"></p> 
    <% if @products > $max_products %>
      <h6>You can only have <%= $max_products %> products posted at once.</h6>
      <%= f.button "Post Product", class: "btn btn-primary btn-post card", disabled: true, id: "product-submit-btn", style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
    <% else %>
      <%= f.button "Post Product", class: "btn btn-primary btn-post", id: "product-submit-btn", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i> Posting Product...".html_safe, style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
    <% end %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="col-lg-3 col-md-4 col-sm-6 mb-4 product-container">
  <div class="card h-100 product-container-card">
    <% if product.images.present? %>
		<div class="scroller">
			<% product.images.each do |p| %>
					<%= link_to product do %>
						<%= image_tag(p.url, class: "image-container") %>
					<% end %>
			<% end %>
		</div>
	<% else %>
		<%= link_to product do %>
			<%= image_tag("no-image.png", alt: "Default Profile Pic", class: "image-container no-image") %>
		<% end %>
	<% end %>
    <div class="card-body">
      <h4 class="card-title product-title">
        <%= link_to product do %>
			<span style="color: <%= @market.first_color %>"><%= sanitize markdownify product.title %></spam>
		<% end %>
      </h4>
      <h5>$<%= product.price %></h5>
      <h5 class="card-text product-description"><%= sanitize markdownify product.description %></h5>
    </div>
    <div class="card-footer">
      <small><%= local_time_ago product.created_at %></small>
	  <span class="product-category"><%= markdownify product.category.icon %></span>
<!--       <% if @user.present? %>
		<%= form_for @flag, url: product_flag_path do |f| %>
			<%= f.hidden_field :product_id, :value => product.id %>
			<%= f.hidden_field :user_id, :value => @user.id %>
			<%= f.button '<i class="fa fa-flag-o" aria-hidden="true"></i>'.html_safe, :onclick => "if(!confirm(\'Are you sure you want to report this product?\')) return false;", class: "btn-flag", style: "color: #{ @market.first_color }" %>
		<% end %>
	  <% else %> -->
	  <!-- <% end %> -->
    </div>
    
  </div>
</div>

app/views/products/_sidenav.html.erb
<div class="col-sm-3 col-md-2 hidden-xs hidden-sm sidenav-container-desktop">
	<div class="sidenav card">
		<%= search_form_for @q, html: { class: "form-inline category_id sidenav-categories"} do |f| %>
			<h6 class="market-highlight" style="color: <%= @market.first_color %>">Categories</h6>
			<% Category.all.order("category_name asc").each do |category| %>
	        	<label class="sidenav-category-label">
	        		<%= f.check_box :category_id_in, {class: "checkbox inline", multiple: true, include_blank: true, onchange: 'this.form.submit();' }, category.id, nil %>
	        		<%= markdownify category.icon %> <%= category.category_name %>
	        	</label>
	      	<% end %>

	      	<hr>
	      	<h6 class="market-highlight" style="color: <%= @market.first_color %>">Price</h6>

			<%= f.number_field :price_gteq, placeholder: "Low", class: "form-control sidenav-price-label" %> 
				to 
			<%= f.number_field :price_lteq, placeholder: "High", class: "form-control sidenav-price-label" %>
		    <%= f.button '<i class="fa fa-chevron-right" aria-hidden="true"></i>'.html_safe, class: "btn btn-primary card", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'>".html_safe, style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
		<% end %>
	</div>
</div>

<div class="visible-xs visible-sm">
    <div class="navbar-header">
      <button class="col-xs-4 sidenav-container sidenav-container-filters navbar-toggle" type="button" data-toggle="collapse" data-target=".cs-navbar-collapse">
        <h6 class="sidenav-filters-header" style="color: <%= @market.first_color %>"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Filters</h6>
      </button>
      <%= button_to 'Post Product', new_product_path, :method => :get, class: "col-xs-8 sidenav-container sidenav-container-filters navbar-toggle", style: "background-color: #{@market.first_color}; color: white" %>
    </div>

    <nav class="collapse navbar-collapse cs-navbar-collapse " role="navigation">
      <ul class="nav navbar-nav">
      	<%= search_form_for @q, html: { class: "form-inline category_id sidenav-categories"} do |f| %>
			<h6 class="market-highlight" style="color: <%= @market.first_color %>">Categories</h6>
			<% Category.all.order("category_name asc").each do |category| %>
	        	<label class="sidenav-category-label">
	        		<%= f.check_box :category_id_in, {class: "checkbox inline", multiple: true, include_blank: true, onchange: 'this.form.submit();' }, category.id, nil %>
	        		<%= markdownify category.icon %> <%= category.category_name %>
	        	</label>
	      	<% end %>

	      	<hr>
	      	<h6 class="market-highlight" style="color: <%= @market.first_color %>">Price</h6>

			<%= f.search_field :price_gteq, placeholder: "Low", class: "form-control sidenav-price-label" %> 
				to 
			<%= f.search_field :price_lteq, placeholder: "High", class: "form-control sidenav-price-label" %>
		    <%= f.button '<i class="fa fa-chevron-right" aria-hidden="true"></i>'.html_safe, class: "btn btn-primary card", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'>".html_safe, style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
		<% end %>
	  </ul>
    </nav>
</div>

app/views/products/_subnav.html.erb
<div class="content-container">
	<div>
	<%= search_form_for @q, html: { class: "form-inline category_id card"} do |f| %>
		<div class="form-group form-search" id="input-container">
	    <%= f.search_field :title_cont, placeholder: "Search...", autofocus: true, class: "form-control form-search", id: "input-social" %>
	    <i class="fa fa-search" aria-hidden="true" id="input-social-icon"></i>
		</div>
	    <%= f.button "Search", class: "card btn btn-primary btn-search hidden-xs hidden-sm", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i>".html_safe, style: "background-color: #{@market.first_color}; border-color: #{@market.first_color}" %>
	<% end %>
	</div>
</div>

app/views/products/edit.html.erb
<div class="container">
	<h1>Editing Product</h1>
	<%= render "form" %>
</div>

app/views/products/index.html.erb
<% if @banner.product_index.present? %>
  <div class="alert alert-info alert-dismissable">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <%= @banner.product_index %>
</div>
<% end %>

<%= render partial: "products/subnav" %>
<div class="content-container">
  <h1 class="page-header">Marketplace</h1>
  <%= render partial: "products/sidenav" %>
  <div class="col-sm-9 col-md-10 container-mobile container-mobile-product"> 
  	<%= render @products %>
    <div class="col-md-12">
      <%= will_paginate @products %>
    </div>
  </div>  
</div>

app/views/products/new.html.erb
<% if @banner.product_new.present? %>
    <div class="alert alert-info alert-dismissable">
  		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  		<%= @banner.product_new %>
	</div>
<% elsif @products > $max_products %>
	<div class="alert alert-danger alert-dismissable">
  		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  		You can only have <%= $max_products %> products posted at once.
	</div>
<% end %>

<div class="container">
	<h1>New Product</h1>

	<%= render "form" %>
</div>

app/views/products/show.html.erb
<% if @banner.product_show.present? %>
    <div class="alert alert-info alert-dismissable">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  	<%= @banner.product_show %>
  </div>
<% end %>
<div class="container mobile-container">
  <!-- Portfolio Item Heading -->
  

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-7 show-images-container">
    <% if @product.images.present? %>
			<div class="slider slider-for">
				<% @product.images.each do |p| %>
					<div><%= image_tag(p.url, class: "show-image-container") %></div>
				<% end %>
			</div>
			<div class="slider slider-nav">
				<% @product.images.each do |p| %>
					<div><%= image_tag(p.url, class: "show-image-selection-container") %></div>
				<% end %>
			</div>
		<% else %>
			<div><%= image_tag("no-image.png", alt: "Default Profile Pic", class: "image-container no-image show-no-image") %></div>
		<% end %>
    </div>

    <div class="col-md-5 show-details-container card">
      <h3>
        <% if @product.user.images.present? %><%= image_tag(@product.user.images.url, class: "profile-image-container") %><% else %><%= image_tag("no-profile.png", class: "profile-image-container") %><% end %> <%= @product.user.username %></h3>
      <% if current_user.present? || (current_user.present? && current_user.is_advertiser != true) %>
    	  <h4 class="social-icons">
    		<% if @product.user.facebook? %>
          <a href="http://www.facebook.com/<%= @product.user.facebook %>" target="_blank"><i class="fa fa-facebook" aria-hidden="true" style="color: <%= @market.first_color %>"></i></a>
        <% end %>
        <% if @product.user.instagram? %>
    		  <a href="http://www.instagram.com/<%= @product.user.instagram %>" target="_blank"><i class="fa fa-instagram" aria-hidden="true" style="color: <%= @market.first_color %>"></i></a>
        <% end %>
<!--         <% if @product.user.snapchat? %>
    		  <a href="#"><i class="fa fa-snapchat" aria-hidden="true" style="color: <%= @market.first_color %>"></i></a>
        <% end %> -->
        <% if @product.user.twitter? %>
    		  <a href="http://www.twitter.com/<%= @product.user.twitter %>" target="_blank"><i class="fa fa-twitter" aria-hidden="true" style="color: <%= @market.first_color %>"></i></a>
        <% end %>
    	  </h4>
      <% end %>
      <p><%= local_time_ago @product.created_at %></p>
      <hr>
      <h2 class="my-4"><%= sanitize markdownify @product.title %></h2>
      <h4 style="color: <%= @market.first_color %>;">$<%= @product.price %></h4>
      <h4 class="my-3">Product Description</h4>
      <p><%= sanitize markdownify @product.description %></p>
      <hr>
      <div class="btn btn-contact-info btn-gradient btn-block card" style="background: <%= @market.first_color %>;  background: -webkit-linear-gradient(left, <%= @market.first_color %> , <%= @market.second_color %>); background: -o-linear-gradient(right, <%= @market.first_color %>, <%= @market.second_color %>); background: -moz-linear-gradient(right, <%= @market.first_color %>, <%= @market.second_color %>); background: linear-gradient(to right, <%= @market.first_color %> , <%= @market.second_color %>);">Contact Seller</div>
		<div class="show-contact-info show-contact-info-hidden">
    <% if current_user.present? %>
        <h5>Contact Details:</h5>
				<p><i class="fa fa-envelope" aria-hidden="true"></i> <%= sanitize @product.user.email %></p>
				<% if @product.user.phone_number? %>
					<p><i class="fa fa-phone" aria-hidden="true"></i> <%= sanitize @product.user.phone_number %></p>
				<% elsif @product.contact_pref? %>
					<p><i class="fa fa-phone" aria-hidden="true"></i> <%= sanitize @product.contact_pref %></p>
				<% end %>
    <% else %>
      <h5><%= link_to "Sign up to see contact details.", new_user_registration_path() %></h5>
    <% end %>
		</div>
	</div>
</div>

    
  </div>